# Generated by Django 3.1.4 on 2021-02-19 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210210_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CustomiztionGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('customiztion_type', models.CharField(choices=[('OPTIONAL', 'Optional'), ('REQUIRED', 'Required')], max_length=20, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
        migrations.CreateModel(
            name='Customization_Items',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('customiztion_type', models.CharField(choices=[('PAID', 'Paid'), ('FREE', 'Free')], max_length=20, null=True)),
                ('customiztionGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.customiztiongroup')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
    ]
