# Generated by Django 3.1.4 on 2021-01-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210125_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prepare_time',
            field=models.IntegerField(default=0),
        ),
    ]
