# Generated by Django 3.1.7 on 2021-03-02 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20210302_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopbranch'),
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('category', 'menu')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('category', 'item')},
        ),
    ]
