# Generated by Django 3.1.4 on 2021-02-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210210_2233'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(default='69eccffc-b155-4b56-858d-a5d039b6c505', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='street_address',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
