# Generated by Django 3.1.4 on 2021-02-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Documents Requested'), (2, 'Approved'), (3, 'Cancelled'), (4, 'Rejected')], default=0),
        ),
    ]
