# Generated by Django 3.1.4 on 2021-01-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usertype'),
        ),
    ]
