# Generated by Django 3.1.7 on 2021-03-03 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210302_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cusine',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
