# Generated by Django 3.1.4 on 2021-01-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210121_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alpha_two_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
