# Generated by Django 3.1.4 on 2021-01-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210123_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbranch',
            name='branch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.branchtype'),
        ),
    ]
