# Generated by Django 3.1.4 on 2021-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shop_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbranch',
            name='perm',
        ),
        migrations.AddField(
            model_name='userbranch',
            name='permission',
            field=models.IntegerField(choices=[(0, 'Viewer'), (1, 'Moderator'), (2, 'Editor'), (3, 'Admin')], default=0),
        ),
    ]
