# Generated by Django 3.1.4 on 2021-01-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210127_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='shopbranch',
            options={'verbose_name_plural': 'Shop Branches'},
        ),
        migrations.AlterModelOptions(
            name='userbranch',
            options={'verbose_name_plural': 'User Branches'},
        ),
    ]
